### ISSUE TITLE
Node 6.1 initial npm install fails

### ISSUE THREAD

**Issue by localnerve** [localnerve/react-pwa-reference#3]
The initial npm install fails in node 6.1 environment. In the post install, gulp 4 can't find babel-register even though it does exist in node_modules (it was installed, after all).

This only effects Node 6.1.0. confirmed it does not exist in 4.4.4, 5.10.1.

error output:
```
> react-pwa-boilerplate@0.1.0 postinstall /home/agrant/src/localnerve/react-pwa-reference
> gulp symlinkSrc

[13:59:33] Failed to load external module babel-register
[13:59:33] Failed to load external module babel-core/register
[13:59:33] Failed to load external module babel/register
/home/agrant/src/localnerve/react-pwa-reference/gulpfile.babel.js:5
import gulp from 'gulp';
^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at execute (/home/agrant/src/localnerve/react-pwa-reference/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js:33:18)
    at Liftoff.handleArguments (/home/agrant/src/localnerve/react-pwa-reference/node_modules/gulp/node_modules/gulp-cli/index.js:150:63)
```

**Comment by localnerve** [comment]
Running gulp in the postinstall also causes problems on deployments, because it requires devDeps. Trying to run gulp here is too big of a problem to keep, replacing with straight-up node script.
